### ISSUE TITLE
Poner el código de la oca sobre el que se está trabajando

### ISSUE THREAD

**Issue by ghost** [yunaii03/Proyecto-PHYTON#2]
Hola, quiero ver el código de la oca sobre el que se está trabajando en el github. Así lo puedo probar y revisar.

**Comment by yunaii03** [comment]
Buenos dias Xavi,
Ayer te dije que Joan y yo continuariamos con la Oca, pero me dejé el disco
duro donde tenía una parte del juego y por eso, en vez de seguir con la
oca, empezamos todos con Batalla Naval, te invité al proyecto en Github y
ayer ya subimos todo lo que hicimos.
Perdona por no avisarte de que cambiamos la dinamica ayer.
Atentamente,
Yunai.

**Comment by ghost** [comment]
De acuerdo, no obstante, deberíais limpiar un poco el código de la oca para que sea más claro y empezar a hacer las pruebas finales de la oca. Si subís el código me lo puedo mirar con más calma
